package:
  # Short name to avoid filename length issues on Windows.
  name: projtemplate
  version: {{ cookiecutter.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pybind11
    - cmake
    - ninja
    - pkg-config
    - setuptools-rust

outputs:
  - name: libprojcxx
    build:
      activate_in_script: True
    script: install-libprojcxx.sh   # [unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - pybind11
        - python

  - name: pyproj
    script: install-pyproj.sh   # [unix]
    build:
      activate_in_script: True
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - pybind11
        - cmake
        - ninja
        - pkg-config
        - setuptools-rust
        - python
      run:
        - python
    test:
      source_files: src/python/*
      requires:
        - pytest
        - flake8
      commands:
        - flake8 src/python
        - pushd src/python/project/tests
        -   pytest -sv
        - popd

about:
  home: https://extropic.net/
  license: Propriatary
  license_file: LICENSE.txt
  summary: Template python project with c++ and rust bindings.

extra:
  recipe-maintainers:
    - ascislowicz
