package:
  # Short name to avoid filename length issues on Windows.
  name: {{ cookiecutter.project_slug }}
  version: {{ cookiecutter.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - {% raw %}{{ compiler('c') }}{% endraw %}
    - {% raw %}{{ compiler('cxx') }}{% endraw %}
    - {% raw %}{{ compiler('rust') }}{% endraw %}
    - python
    - pybind11
    - cmake
    - ninja
    - pkg-config
    - setuptools-rust

outputs:
  - name: libprojcxx
    build:
      activate_in_script: True
    script: install-libprojcxx.sh   # [unix]
    requirements:
      build:
        - {% raw %}{{ compiler('c') }}{% endraw %}
        - {% raw %}{{ compiler('cxx') }}{% endraw %}
        - cmake
        - ninja
        - pybind11
        - python

  - name: pyproj
    script: install-pyproj.sh   # [unix]
    build:
      activate_in_script: True
    requirements:
      build:
        - {% raw %}{{ compiler('c') }}{% endraw %}
        - {% raw %}{{ compiler('cxx') }}{% endraw %}
        - {% raw %}{{ compiler('rust') }}{% endraw %}
      host:
        - python
        - pybind11
        - cmake
        - ninja
        - pkg-config
        - setuptools-rust
      run:
        - python
    test:
      source_files: src/python/*
      requires:
        - nox
      commands:
        - nox -s tests

about:
  home: https://extropic.net/
  license: Propriatary
  license_file: LICENSE.txt
  summary: Template python project with c++ and rust bindings.

extra:
  recipe-maintainers:
    - ascislowicz
